
volumes:
  db-data:
services:
  server:
    build:
      context: .
    env_file: ".env"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${HTTP_PORT}
    develop:
        watch:
          - action: rebuild
            path: .
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db-data:/var/lib/mysql
#    env_file: ".env"
    environment:
      - MYSQL_DATABASE=myapp
      - MYSQL_ROOT_PASSWORD=root
    ports:
      [ "3306:3306" ]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
