
volumes:
  db-data:
services:
  server:
    build:
      context: .
    env_file: ".env"
    environment:
      NODE_ENV: production
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: myapp
    ports:
      - "3000:3000"
    develop:
        watch:
          - action: rebuild
            path: .
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=myapp
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

#  dbmate:
#    image: ghcr.io/amacneil/dbmate
#    depends_on:
#      - db
#    env_file:
#      - docker.env
#    volumes:
#      - ./db/migrations:/db/migrations
