# fly.toml app configuration file generated for crud-mysql-flyio on 2025-03-14T21:30:10-02:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crud-mysql-flyio'
primary_region = 'yul'

[build]
  image = 'mysql:8'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
    app = """--datadir /data/mysql \
      --default-authentication-plugin mysql_native_password"""

[mounts]
  source = "mysqldata"
  destination = "/data"

[env]
  MYSQL_DATABASE = "my_db"
  MYSQL_USER = "crud_user"
