
volumes:
  db-data:
services:
  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

#  dbmate:
#    image: ghcr.io/amacneil/dbmate
#    depends_on:
#      - db
#    env_file:
#      - docker.env
#    volumes:
#      - ./db/migrations:/db/migrations
