# fly.toml app configuration file generated for db-bold-wave-7350 on 2025-03-15T13:15:13-02:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'db-bold-wave-7350'
primary_region = 'yul'

[build]
  image = 'mysql:8.0'

[env]
  MYSQL_DATABASE = 'myapp'
  MYSQL_USER = 'root'

[processes]
  app = '--datadir /data/mysql --default-authentication-plugin mysql_native_password'

[[mounts]]
  source = 'mysqldata'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
